name: 02 - Workflow Events
on:
  - push
  - pull_request
  - workflow_dispatch
# on:
#     schedule:
#         - cron: '0 0 * * *'
jobs:
  echo-job:
    name: echo
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Commit ID: ${{ github.event.commits.id }}"
